### ISSUE TITLE
Fails with dev versions of Moose

### ISSUE THREAD

**Issue by andk** [rjbs/HTTP-Throwable#6]
Cpantesters have fail reports with Moose 2.130{3,4}. These are dev releases but I thought the sooner we get it on your Todo list the sooner the incompatibility will be resolved. Isn't it? :)

Sample fail report:

http://www.cpantesters.org/cpan/report/46109071

Cheers,

**Comment by karenetheridge** [comment]
I trust this issue has been resolved now? Moose is no longer in a dev cycle.

**Comment by rjbs** [comment]
👍🏽
